// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: images.sql

package database

import (
	"context"
)

const createImage = `-- name: CreateImage :one
insert into images (url, name)
values($1, $2)
returning id
`

type CreateImageParams struct {
	Url  string `json:"url"`
	Name string `json:"name"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (int64, error) {
	row := q.db.QueryRow(ctx, createImage, arg.Url, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
