// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
insert into users (name, email, password_hash)
values ($1, $2, $3)
returning id
`

type CreateUserParams struct {
	Name         string      `json:"name"`
	Email        interface{} `json:"email"`
	PasswordHash []byte      `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}
